name = "digifair-cloudflare-basic-fa"
main = "src/index.ts"
compatibility_date = "2024-07-21"
compatibility_flags = ["nodejs_compat"]

# فقط Node - Python ندارد - بدون فولدر اضافه
[site]
bucket = "./"

[[d1_databases]]
binding = "DB_D1"
database_name = "digifair-fa-basic"
database_id = "xxxx-basic-id"

[[hyperdrive]]
binding = "HYPERDRIVE_PG"
id = "xxxx-hyperdrive-basic-id"
localConnectionString = "postgres://default:xxx@ep-xxx.neon.tech/verceldb?sslmode=require"

[[kv_namespaces]]
binding = "KV_FA"
id = "xxxx-kv-basic-id"

[vars]
DEFAULT_LANG = "fa-IR"
RUNTIME = "cloudflare-basic-node-only - no python"
